### ISSUE TITLE
about setfiles command permission

### ISSUE THREAD

**Issue by zpd2009** [ni/meta-selinux#4]
why meta-selinux can use setfiles command with no root perimission. but when i want to use setfiles command in my .bb file to set selinux label to other image, it will post a "Operation not permitted" error.

thanks

**Comment by amstewart** [comment]
Hey @zpd2009,

Could you provide some more context on what you're trying to accomplish with your BB recipe? And could you also provide your recipe source, to help me understand how you're using setfiles?

**Comment by zpd2009** [comment]
```
DEPENDS += "policycoreutils-native"

IMAGE_NAME = "apps.img"

do_compile() {
    IMAGE_SIZE=1048576
    dd if=/dev/zero of=${IMAGE_NAME} bs=1 count=0 seek=$(expr 1024 \* ${IMAGE_SIZE})

    install -d ${B}/apps

    if [ -f ${APPS_PACK_PATH}/app.tar.gz ];then
      echo "file exist"
      install -d ${B}/apps/
      tar -zxvf ${APPS_PACK_PATH}/app.tar.gz -C ${B}/apps/
    fi

    setfiles -m -r ${B}/ ${DEPLOY_DIR_IMAGE}/file_contexts/file_contexts ${B}/apps
    mkfs.ext4  -F -i 4096 ${IMAGE_NAME}  -d ${B}/apps
    fsck.ext4 -pvfD ${IMAGE_NAME} || [ $? -le 3 ]
}
```
 i want to make a ext4 image with some binary file，but when i use setfiles command to set the selinux label, it will post a "Operation not permitted" error.

setfiles: Could not set context for /data/zpd2009/test-info/build_test/tmp/work/aarch64-fsl-linux/apps/1.0-r0/apps:  Operation not permitted

and i test the command in ubuntu20.04, 
```
setfiles -m -r /data/zpd2009/test-info/build_test/tmp/work/aarch64-fsl-linux/apps/1.0-r0/ ./file_contexts  /data/zpd2009/test-info/build_test/tmp/work/aarch64-fsl-linux/apps/1.0-r0/apps  
```
the setfiles command need root permission.

and i test the meta-selinux's  setfiles comand: 
```
setfiles -m -r ${IMAGE_ROOTFS} ${IMAGE_ROOTFS}/${sysconfdir}/selinux/${POL_TYPE}/contexts/files/file_contexts ${IMAGE_ROOTFS} 
``` 
it also needs root permission, but in yocto meta-selinux environment, the setfiles command can set the selinux label success.

**Comment by zpd2009** [comment]
do_install run in a fakeroot environment. 

thanks.
