### ISSUE TITLE
Building busybox with CONFIG_SELINUX=y fails

### ISSUE THREAD

**Issue by pasweistorz** [ni/meta-selinux#8]
Hi,

we're using your meta-selinux layer and busybox in our system. We have a configuration snippet for busybox which sets `CONFIG_SELINUX=y` in order to be able to use `ps -Z` for example. But we're getting errors when compiling busybox:

```
| In file included from include/busybox.h:8,
|                  from applets/applets.c:9:
| include/libbb.h:83:11: fatal error: selinux/selinux.h: No such file or directory
|    83 | # include <selinux/selinux.h>
|       |           ^~~~~~~~~~~~~~~~~~~
| compilation terminated.
| make[1]: *** [scripts/Makefile.build:198: applets/applets.o] Error 1
| make[1]: *** Waiting for unfinished jobs....
| make: *** [Makefile:372: applets_dir] Error 2
| ERROR: oe_runmake failed
```

It seems that libselinux is missing as a build dependency of busybox. Would it be possible to add libselinux to the dependencies of busybox in your `busybox_selinux.inc` file?

Maybe it would also be a good idea to provide a configuration snippet for busybox with `CONFIG_SELINUX=y` in your layer to have `ps -Z` working out of the box.

I'd be happy to provide a pull request if those changes are fine for you.

Thanks in advance for your response.

**Comment by amstewart** [comment]
Hey.

Are you building the whole NI LinuxRT distro? Or are you building your own OE distro, and just using our fork as your meta-selinux layer?

For either case: The missing libselinux dependency sounds like a fundamental issue with the `busybox_selinux.inc` file. Which should go upstream to [git.yoctoproject.org/meta-selinux](https://git.yoctoproject.org/meta-selinux/) first. Then we can merge it back into this downstream once they've accepted it.

**Comment by pasweistorz** [comment]
Ah, sorry, I wasn't aware that this project is a fork. I thought this is the upstream repository. I'll try to get a fix into the upstream project.

**Comment by amstewart** [comment]
No worries. The only thing we're the upstream for is [meta-nilrt](https://github.com/ni/meta-nilrt).
